#+Title: Photosynthesis quiz
#+AUTHOR:
#+Email:
#+OPTIONS: toc:nil reveal_mathjax:t
#+OPTIONS: num:nil
#+REVEAL_THEME: night
#+REVEAL_TRANS: linear 
#+REVEAL_MARGIN: 0
#+REVEAL_MIN_SCALE: 1
#+REVEAL_MAX_SCALE: 1.5
# +REVEAL_ROOT: ~http://cdn.jsdelivr.net/reveal.js/2.5.0


* What are the products of photosynthesis?
Carbon dioxide and water / Glucose and oxygen / Lactic acid

** What are the products of photosynthesis?
Carbon dioxide and water / *Glucose and oxygen* / Lactic acid

* What colour is chlorophyll?
Black / Blue / Green

** What colour is chlorophyll?
Black / Blue / *Green*

* Where does photosynthesis take place?
In the chloroplasts / In the cell wall / In the nucleus

** Where does photosynthesis take place?
*In the chloroplasts* / In the cell wall / In the nucleus

* What are the reactants of photosynthesis?
Carbon dioxide and water / Carbon dioxide and oxygen / Glucose and oxygen

** What are the reactants of photosynthesis?
*Carbon dioxide and water* / Carbon dioxide and oxygen / Glucose and oxygen

* When do plants respire?
During the day only / During the day and night / During the night only

** When do plants respire?
During the day only / *During the day and night* / During the night only

* When do plants photosynthesise?
During the day and night / During the night only / During the day only

** When do plants photosynthesise?
During the day and night / During the night only / *During the day only*

* What are the cells near the top of leaves called?
Palisade cells / Root hair cells / Red blood cells

** What are the cells near the top of leaves called?
*Palisade cells* / Root hair cells / Red blood cells

* What does xylem carry?
Water / Blood / Carbohydrates

** What does xylem carry?
*Water* / Blood / Carbohydrates

* What do stomata do?
Stop carbon dioxide diffusing into leaves / Allow oxygen to diffuse into leaves / Allow carbon dioxide to diffuse into leaves

** What do stomata do?
Stop carbon dioxide diffusing into leaves / Allow oxygen to diffuse into leaves / *Allow carbon dioxide to diffuse into leaves*

* How are root hair cells adapted?
Huge surface area / Lots of chloroplasts / Have no cell wall

** How are root hair cells adapted?
*Huge surface area* / Lots of chloroplasts / Have no cell wall
